Add delete-button and clear code
svenvonwerner/capstone-project pull request #16
Opened 2022-03-24 16:15 UTC by svenvonwerner

2022-03-24 17:27 UTC, ahohnsen requested changes
Very nice work :) I just have a few little suggestions, have a look

2022-03-24 17:27 UTC, ahohnsen commented on src/components/ChallengeCardList.spec.js
>    it('Render a list of challenge-cards', () => {
```suggestion
  it('renders a list of challenge-cards', () => {
```

:)

2022-03-24 17:27 UTC, ahohnsen commented on src/components/DeleteButton.js
> +`;
Instead of making a component for a delete and a check button, I would recommend to make a general button component as the styles for both are the same. Then you could use the button component for both, the delete and check button. If you only extract the styles into your button component and nothing else, you can then just make a story for it and do not need a test for it, I guess. If you have any questions regarding this, let me know :)

2022-03-25 09:21 UTC, svenvonwerner commented on src/components/ChallengeCard.js
> +export default function ChallengeCard({ headlineCard, descriptionCard, onCheckClick, onDeleteCard, ...props }) {
The intention was to keep the code light. But I see it could be difficult to understand, which props are passed on. I have registered this as an issue on my board.

2022-03-25 09:41 UTC, svenvonwerner commented on src/components/ChallengeCard.spec.js
> +describe('ChallengeCard', () => {
I have registered this as an issue on my board. Thx:)

2022-03-25 10:12 UTC, merged